### ISSUE TITLE
Missing asdf install

### ISSUE THREAD

**Issue by camilohollanda** [cabesa-collective/capistrano-asdf#1]
It would be very nice to be able to run `asdf install`, or `asdf plugin add`.

**Comment by tipoix** [comment]
Hi Prakash,
It's scheduled to be included in next version :-)

**Comment by tipoix** [comment]
Hi Prakash,
Your request has been integrated and is available in the 1.0.0.
**asdf:install** and **asdf:add_plugins**.
See the updated README for more informations.

**Comment by camilohollanda** [comment]
Thank you very much, I will be testing soon.
