### ISSUE TITLE
Systemd

### ISSUE THREAD

**Issue by tomprats** [cabesa-collective/capistrano-asdf#3]
I haven't been able to get asdf and systemd to work together.

The `unicorn_nginx` gem generates a systemd unit with `ExecStart=source /opt/asdf/asdf.sh; bundle exec unicorn`

Which errors with `Failed to locate executable source: No such file or directory`

So it looks like using `source` is an issue. Is there another path to `bundle exec unicorn` that will correctly use asdf?

**Comment by tipoix** [comment]
Hello @tomprats,

I updated the gem to generate and use a wrapper script to avoid sourcing the ASDF environment.
This may also resolve your Systemd unit.

Best regards,
